spring.application.name=shipping
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:smartlogix;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}

#PORT
server.port=${PORT:8084}


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

app.security.admin-email=${ADMIN_EMAIL}
app.security.admin-email-2=${ADMIN_EMAIL_2}
app.metrics.cashflow.unit-value=${CASHFLOW_UNIT_VALUE:12.5}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


#CONFIG DE ENVIO CORREO
mail.provider=${MAIL_PROVIDER:gmail}

# Gmail SMTP
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:465}

# Outlook SMTP (uncomment these 2 lines if you prefer Outlook)
#spring.mail.host=${MAIL_HOST:smtp.office365.com}
#spring.mail.port=${MAIL_PORT:587}

#P: xfiz azpk xlqe jtrj
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.trust=${spring.mail.host}
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000
spring.mail.default-encoding=UTF-8
