-- FlashStock Inventory DEV: matched against four @Entity classes in the inventory module.
-- Run ONCE with the managed RDS credential via ECS migration task; no public DB port.
-- Idempotent for a new empty database; NOT a general-purpose upgrade migration.
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku VARCHAR(255) NOT NULL UNIQUE,
  supplier_id BIGINT,
  quantity INTEGER NOT NULL,
  stock INTEGER,
  warehouse VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1200),
  unit_price NUMERIC(12,2) NOT NULL,
  price NUMERIC(12,2),
  image_url VARCHAR(1024),
  category VARCHAR(100),
  active BOOLEAN NOT NULL,
  version BIGINT
);
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email VARCHAR(250) NOT NULL,
  sku VARCHAR(100) NOT NULL,
  inventory_id BIGINT,
  quantity INTEGER NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_cart_user_sku UNIQUE(user_email,sku)
);
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(255) NOT NULL UNIQUE,
  sku VARCHAR(255) NOT NULL,
  inventory_id BIGINT,
  quantity INTEGER NOT NULL,
  customer_first_name VARCHAR(255),
  customer_last_name VARCHAR(255),
  customer_email VARCHAR(255),
  shipping_address VARCHAR(255),
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE IF NOT EXISTS shipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_number VARCHAR(255) NOT NULL UNIQUE,
  order_number VARCHAR(255) NOT NULL,
  carrier VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  eta VARCHAR(255) NOT NULL,
  courier_name VARCHAR(255),
  origin_lat DOUBLE PRECISION,
  origin_lng DOUBLE PRECISION,
  destination_lat DOUBLE PRECISION,
  destination_lng DOUBLE PRECISION,
  courier_lat DOUBLE PRECISION,
  courier_lng DOUBLE PRECISION,
  route_geo_json TEXT,
  route_steps_json TEXT,
  total_duration_sec INTEGER,
  created_at TIMESTAMP(6),
  last_update TIMESTAMP(6)
);
CREATE TABLE IF NOT EXISTS delivery_drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL,
    vehicle VARCHAR(255),
    plate VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    current_lat NUMERIC(10,7),
    current_lng NUMERIC(10,7),
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cart_items_sku ON cart_items(sku);
CREATE INDEX IF NOT EXISTS idx_shipments_order_number ON shipments(order_number);
